### ISSUE TITLE
Separate import/export file format listings

### ISSUE THREAD

**Issue by soxofaan** [openEOPlatform/documentation#13]
Minor issue: at first impression there seems to be duplication of the GTiff format in the file format listing at https://docs.openeo.cloud/file-formats/ 

![Screenshot from 2021-08-25 18-12-50](https://user-images.githubusercontent.com/44946/130826708-4c279b99-9c27-4af7-8015-bbb03034b839.png)

One is about import and the other is for exports, but that is not very obvious.

Maybe it will look better if import and export formats are listed separately in two sections or side by side columns?

**Comment by m-mohr** [comment]
No problem. Is it better now?

**Comment by soxofaan** [comment]
that was quick :)
