### ISSUE TITLE
Feature Engineering example issues

### ISSUE THREAD

**Issue by m-mohr** [openEOPlatform/documentation#14]
It seems the Feature Engineering example notebook is hosted at notebooks.terrascope.be, which I don't see EGI login being available for. So it seems inaccessible and should be fixed?

https://docs.openeo.cloud/usecases/feature-engineering/

Also, there's an incomplete sentence in the docs:

> To correctly compute and use statistics over a timeseries, gap-free composites at fixed timesteps are n

**Comment by jdries** [comment]
I fixed the link, as we indeed did not want to reference a specific jupyterlab. (Terrascope notebooks do work with EGI, choose 'Edugain& social'.)
The issue in the text seems to be fixed already, but text itself may need a bit of work.
