### ISSUE TITLE
Process description link for openeo.cloud

### ISSUE THREAD

**Issue by clausmichele** [openEOPlatform/documentation#16]
One of the RIDs for SRR2 was: 
_Could the provided hyperlinks be updated to refer to   https://docs.openeo.cloud/processes/ instead of openeo.org?_

@m-mohr currently this is not possible right? Or is there a way to visualize it using the link only?

![image](https://user-images.githubusercontent.com/31700619/134294000-24df9d87-38f9-460c-8ce5-0b92c0c3eb80.png)

**Comment by m-mohr** [comment]
It is possible, just add the name at the end with a leading `#`:

Example: https://docs.openeo.cloud/processes/#date_shift

**Comment by clausmichele** [comment]
Thanks!
