### ISSUE TITLE
Redundant link to Cookbook

### ISSUE THREAD

**Issue by bschumac** [openEOPlatform/documentation#37]
There is a redundant link to the openeo.org cookbook under the menu items "Get started" and "Use Cases".
It would take me significant time to delete it. Could someone who is more familiar with the docs page please quickly do that?
Thanks!

**Comment by m-mohr** [comment]
It's redundant intentionally as it fits into both categories and wherever people look for it, they can find it quickly.

Is there an issue with it? If yes, we can probably remove it from use cases and move it up a bit in Get Started...

**Comment by bschumac** [comment]
No problem per se. I was just thinking it is unneccessary to link it under Use Cases as the cookbook don't directly relate to the topics of the cookbook. Or what do you mean by "fits in both categories"?

**Comment by m-mohr** [comment]
My intention behind the "use cases" category was "use-cases the user may have", not "use cases in a (random) project the user may not even know specifics about". The cookbook describes use cases the user may stumble across...

**Comment by bschumac** [comment]
Ah okay, so I misunderstood the "use cases" section. That's fine then, I will close the issue.
