### ISSUE TITLE
Make collection federation docs page accessible

### ISSUE THREAD

**Issue by dthiex** [openEOPlatform/documentation#38]
When preparing for SRR3 I realized that our page on the collection federation aspect it's not visible/accessible on the homepage (or I failed to find where).

Link: https://docs.openeo.cloud/federation/backends/collections.html#sentinel2-l2a

I see two options where to put this:
1)  add a new subtab to "Advanced" tab called "Federation Collections"
2) integrate it in the "Federation Aspects" page as we already have a chapter data collections there. 
3) Integrate it as subtab in the "Data collections" tab

I am in favour of option 1 as
- I like that a collection overview via 3) is directly accessible with only one click and find 2 already cluttered/filled enough. 
- I suspect with time more and more info will be added here so it should be it's own page

@m-mohr @jdries @bschumac Any preferences?

**Comment by m-mohr** [comment]
It is accessible via Advanced > Federation Contract > Collections. I think this can be closed.

**Comment by dthiex** [comment]
Somehow missed that, thanks for pointing this out! Location makes sense, I was just looking at the wrong spots and then overlooked it. Can indeed be closed then.
