### ISSUE TITLE
Getting started guides: Elaborate on batch jobs and process creation

### ISSUE THREAD

**Issue by m-mohr** [openEOPlatform/documentation#47]
Feedback from the UCE:
- [x] We should highlight in the docs that you can logout during batch jobs and they continue to run and you can retrieve the results later. We should also highlight that this is not possible for synchronous processing.
- [x] We should highlight that the process creation is only creating a local representation of the process that is sent to the back-end and that what you get back for each step is just a representation of that, not actual data.

**Comment by bschumac** [comment]
From my point of view https://github.com/openEOPlatform/documentation/pull/66 resolves this. Let me know if any further changes are needed!

**Comment by bschumac** [comment]
Pull-request merged. Closing.
