### ISSUE TITLE
Document openEO Platform VO user roles

### ISSUE THREAD

**Issue by soxofaan** [openEOPlatform/documentation#48]
spin off from https://github.com/openEOPlatform/architecture-docs/issues/253:
document the mapping of user levels (early adopter, 30day-trial, university student, ...)  to  the user roles assigned in the EGI user management tool (exposed under `eduperson_entitlement` field to back-ends and aggregator)

I think it makes sense to list this mapping here: https://docs.openeo.cloud/federation/backends/api.html#authorization  (this file in github: https://github.com/openEOPlatform/documentation/blob/main/federation/backends/api.md#entitlements)

**Comment by bschumac** [comment]
Definition of User roles within the EGI openEO Platform Virtual Organisation (VO):


| Agreed Role Name  | EGI User Community Role Title (co_person_roles = strings to check)|
| ------------- | ------------- |
| 30-day trial  | 30-Day-Trial  |
| Early Adopter  | Early_Adopter  |
| Basic  | Basic_User  |
| Advanced/Professional | Professional_User   |
| University student  | University_Student  |
| University & Research Institute  | University_Group_License |
| Platform Developer (PROPOSAL)  | Platform_Developer (PROPOSAL)  |

Roles as defined in ESA NoR:
![grafik](https://user-images.githubusercontent.com/10756379/183961851-3470b50b-c2e1-493e-97a1-7043b493c550.png)

**Comment by bschumac** [comment]
My proposal has been accepted by all. I will add the Developer role to all devs and managers within the next weeks.
